// swift-tools-version:5.9
import PackageDescription

// GENERATED by scripts/publish-xcframework.sh — do not edit the binaryTarget by hand.
let package = Package(
    name: "OSTUIKitKMP",
    platforms: [.iOS(.v16)],
    products: [
        .library(name: "OSTUIKitKMP", targets: ["OSTUIKitKMP"])
    ],
    dependencies: [
        // Native OneStep iOS SDK. The permission flow is vendored so this package
        // has NO dependency on the native iOS UIKit.
        .package(url: "https://github.com/OneStepRND/onestep-sdk-ios", exact: "2.3.1")
    ],
    targets: [
        .binaryTarget(
            name: "OSTUIKit",
            url: "https://github.com/OneStepRND/onestep-uikit-kmp/releases/download/uikit-kmp-0.6.31-SNAPSHOT/OSTUIKit.xcframework.zip",
            checksum: "6c1121fb4e35f64b3f5615f200bb1443b8c3c9bc8db8085ffb1d016f279d0014"
        ),
        .target(
            // Target name == Swift module name: must match the product so `import OSTUIKitKMP` works.
            name: "OSTUIKitKMP",
            dependencies: [
                "OSTUIKit",
                .product(name: "OneStepSDK", package: "onestep-sdk-ios")
            ],
            path: "uikit-kmp/OSTUIKitKMP/Sources",
            resources: [
                .copy("Resources/compose-resources"),
                .process("Resources/Media.xcassets"),
                .process("Resources/Fonts.xcassets"),
                .process("Resources/Localizable.xcstrings")
            ]
        )
    ]
)
