// swift-tools-version:5.9
import PackageDescription

// GENERATED by scripts/publish-xcframework.sh — do not edit the binaryTarget by hand.
let package = Package(
    name: "OSTUIKitKMP",
    platforms: [.iOS(.v16)],
    products: [
        .library(name: "OSTUIKitKMP", targets: ["OSTUIKitKMP"])
    ],
    dependencies: [
        // Native OneStep iOS SDK. The permission flow is vendored so this package
        // has NO dependency on the native iOS UIKit.
        .package(url: "https://github.com/OneStepRND/onestep-sdk-ios", exact: "2.0.8-rc1")
    ],
    targets: [
        .binaryTarget(
            name: "OSTUIKit",
            url: "https://github.com/OneStepRND/onestep-uikit-kmp/releases/download/uikit-kmp-0.2.0-SNAPSHOT/OSTUIKit.xcframework.zip",
            checksum: "03baf2d948019adb20fccd0ccee1358940eecd2f3e0788159a40f974af4174a4"
        ),
        .target(
            // Target name == Swift module name: must match the product so `import OSTUIKitKMP` works.
            name: "OSTUIKitKMP",
            dependencies: [
                "OSTUIKit",
                .product(name: "OneStepSDK", package: "onestep-sdk-ios")
            ],
            path: "uikit-kmp/OSTUIKitKMP/Sources",
            resources: [
                .copy("Resources/compose-resources"),
                .process("Resources/Media.xcassets"),
                .process("Resources/Fonts.xcassets"),
                .process("Resources/Localizable.xcstrings")
            ]
        )
    ]
)
