import java.util.Properties
import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework

// Shared test-app UI (unpublished): the single source of truth for the test harness screens,
// consumed by androidTestApp (project dep) and iosTestApp (via the OSTUIKit framework below).
plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.kotlin.compose.compiler)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.android.kmp.library)
}

// Test-org credentials (API keys + identity-verification secrets) are NOT committed.
// They are read from the gitignored secrets.properties at the repo root (see
// secrets.properties.template) and generated into TestOrgSecrets.kt at build time.
val generateTestAppSecrets by tasks.registering {
    val propsFile = rootProject.file("secrets.properties")
    val outDir = layout.buildDirectory.dir("generated/secrets/kotlin")
    if (propsFile.exists()) inputs.file(propsFile)
    outputs.dir(outDir)
    doLast {
        val props = Properties()
        if (propsFile.exists()) {
            propsFile.inputStream().use { props.load(it) }
        } else {
            logger.warn(
                "secrets.properties not found at repo root — TestOrgSecrets will be empty and " +
                    "SDK activation will fail at runtime. Copy secrets.properties.template and fill it in.",
            )
        }
        fun prop(key: String) = props.getProperty(key) ?: ""
        val file = outDir.get().file("TestOrgSecrets.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// GENERATED by the generateTestAppSecrets task from secrets.properties — do not edit.
            |package co.onestep.kmp.uikit.testapp
            |
            |internal object TestOrgSecrets {
            |    const val SDK_TESTING_API_KEY = "${prop("sdkTesting.apiKey")}"
            |    const val SDK_TESTING_IDENTITY_SECRET = "${prop("sdkTesting.identitySecret")}"
            |    const val ZIMMER_DEV_API_KEY = "${prop("zimmerDev.apiKey")}"
            |    const val ZIMMER_DEV_IDENTITY_SECRET = "${prop("zimmerDev.identitySecret")}"
            |    const val APP_CLIP_API_KEY = "${prop("appClip.apiKey")}"
            |    const val APP_CLIP_IDENTITY_SECRET = "${prop("appClip.identitySecret")}"
            |}
            |
            """.trimMargin(),
        )
    }
}

kotlin {
    targets.configureEach {
        compilations.configureEach {
            compileTaskProvider.configure {
                compilerOptions {
                    freeCompilerArgs.add("-Xexpect-actual-classes")
                }
            }
        }
    }

    androidLibrary {
        namespace = "co.onestep.kmp.uikit.testapp.shared"
        compileSdk = 37
        minSdk = 28
        experimentalProperties["android.experimental.kmp.enableAndroidResources"] = true
    }

    // The test-app framework keeps the library's module name (OSTUIKit) and re-exports
    // :uikit-kmp, so the OSTUIKitKMP Swift package (bridges + SwiftUI wrappers) compiles
    // against it unchanged. Built only by iosTestApp/rebuild.sh — never published.
    val xcf = XCFramework("OSTUIKit")
    listOf(
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "OSTUIKit"
            isStatic = true
            xcf.add(this)
            export(project(":uikit-kmp"))
            export(libs.onestep.design.system)
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateTestAppSecrets)
        }

        commonMain.dependencies {
            api(project(":uikit-kmp"))
            api(libs.onestep.design.system)
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.components.uiToolingPreview)
            implementation(libs.kotlinx.serialization.json)
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:${libs.versions.coroutines.get()}")
        }

        androidMain.dependencies {
            // Native OneStep Android SDK — the Android TestAppShell implementation lives here.
            val githubSnapshot = (findProperty("githubSnapshot") as String?)?.toBoolean() == true
            val coreVersion = (findProperty("coreVersion") as String?)
                ?: if (githubSnapshot) {
                    "${libs.versions.coreVersion.get()}-SNAPSHOT"
                } else {
                    libs.versions.coreVersion.get()
                }
            implementation("co.onestep.android:core:$coreVersion")
        }
    }
}

